# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2441dc6a2a66b95f5ffafcfbe1dd6f221ec3f6ce94944e6773e1dde60099ce992f82342d8425c454a77b26040de073fd09549ab50fa80d87207d03a3a6d7abb2

test:
  secret_key_base: 326300ec55f04eda3457c5cc1e310c78ac15e34ae93e4643fb7120d3ea7bf7b91863537cbd50e30e4dea39e00369c6f45edae16f7ac7c7db932a57f16304d2a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
